name: ddp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda=12.1  # Match with CUDA 12.2 module
  - pip
  - pip:
    - torch>=2.0.0

